#!/bin/bash

TEMP_FILE=$(mktemp)
cd `git rev-parse --show-toplevel`
git ls-files | sort > "$TEMP_FILE"

if [ ! -f .tree ]; then
  mv "$TEMP_FILE" .tree
else
  if ! cmp -s .tree "$TEMP_FILE"; then
    mv "$TEMP_FILE" .tree
  else
    rm "$TEMP_FILE"
  fi
fi
