name: Build and test
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Update
        run: sudo apt-get update
      - name: Install ImageMagick
        run: sudo apt-get -y install graphicsmagick
      - name: checkout
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - run: npm install
      - run: make
      - run: make lint
      - run: make skipped_tests
      - run: make test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
