name: Supabase Ping

on:
  schedule:
    - cron: "25 18 * * 1,5"

defaults:
  run:
    working-directory: docs

jobs:
  supabase_ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Ping Supabase cloud 10 times
        run: |
          for i in {1..10}; do
            echo "### Run #$i"
            npx ts-node supabase.ts
          done
